spring:
  profiles:
    active:
      - dev
---
server:
  port: 8201
spring:
  profiles: dev
  application:
    name: txservice-config-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
---
server:
  port: 8202
spring:
  profiles: test
  application:
    name: txservice-config-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
